name: Secret Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Print environment variables
      run: printenv

    - name: Use secret
      run: echo "${{ secrets.parivaar }}"
