name: Secret Workflow

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use secret
      run: echo "PARIVAAR=${{ secrets.PARIVAAR }}"
